spring:
  datasource:
    username: myuser
    password: secret
    url: jdbc://postgresql://localhost:5432/mydatabase
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
