spring:
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:5432/mydatabase
  sql:
    init:
      mode: always

  security:
    user:
      name: user
      password: 1234
server:
  port: 8081
logging:
  level:
    org:
     springframework:
      jdbc: DEBUG
